version: "3"

services:
  app:
    container_name: app
    build: .
    environment:
      - SOCIAL_AUTH_VK_OAUTH2_KEY=51914636
      - SOCIAL_AUTH_VK_OAUTH2_SECRET=7tr9qkZ18TTQfOeZkjVg
    command: sh -c "python app/manage.py makemigrations
      && python app/manage.py migrate
      && python app/manage.py collectstatic --no-input
      && python app/manage.py loaddata data.json
      && python app/manage.py runsslserver 0.0.0.0:443"
    volumes:
      - .:/app
    ports:
      - 443:443
    depends_on:
      - pgdb

  pgdb:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_NAME=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - pgdbdata:/var/lib/postgresql/data/
volumes:
  pgdbdata:
